### ISSUE TITLE
Node App.js error

### ISSUE THREAD

**Issue by pvrao80** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#15]
Hi, 

I am unable to root cause this particular error. Could someone help me ?

$ node app.js
{"name":"AzureAD: OIDC Passport Strategy","hostname":"INFEHDL234","pid":3236,"level":40,"msg":"Production environments should always validate the issuer.","time":"2017-11-16T19:55:21.075Z","v":0}
{"name":"AzureAD: OIDC Passport Strategy","hostname":"INFEHDL234","pid":3236,"level":40,"msg":"Using http for redirectUrl is not recommended, please consider using https","time":"2017-11-16T19:55:21.075Z","v":0
}
(node:3236) DeprecationWarning: `open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`. See http://mongoosejs.com/
docs/connections.html#use-mongo-client

events.js:160
      throw er; // Unhandled 'error' event
      ^
MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (C:\Pradeep\AWS\passport-azure-ad-login-oidc\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (C:\Pradeep\AWS\passport-azure-ad-login-oidc\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Connection.g (events.js:292:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (C:\Pradeep\AWS\passport-azure-ad-login-oidc\node_modules\mongodb-core\lib\connection\connection.js:187:49)
    at Socket.g (events.js:292:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1277:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)

**Comment by MarkHerhold** [comment]
@pvrao80 You don't have mongoDB running or it's misconfigured. You should either set it up or run the app without by setting `exports.useMongoDBSessionStore = false;` in `config.js`.

**Comment by navyasric** [comment]
Closing as issue is answered in above comment.
