### ISSUE TITLE
Cannot use behind proxy

### ISSUE THREAD

**Issue by mplwork** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#24]
I have to get this work through our corporate proxy. The example completely ignores proxy settings. I tried to add `global-tunnel-ng` like so

```
diff --git a/app.js b/app.js
index fd3e488..c9b9bba 100644
--- a/app.js
+++ b/app.js
@@ -27,6 +27,7 @@
  * Module dependencies.
  *****************************************************************************/

+var globalTunnel = require('global-tunnel-ng').initialize();
 var express = require('express');
 var cookieParser = require('cookie-parser');
 var expressSession = require('express-session');
diff --git a/package.json b/package.json
index d1bc6b6..c12ace8 100644
--- a/package.json
+++ b/package.json
@@ -11,6 +11,7 @@
     "ejs-locals": ">= 0.0.0",
     "express": "3.x",
     "express-session": "^1.14.1",
+    "global-tunnel-ng": "^2.6.0",
     "method-override": "^2.3.6",
     "mongoose": "^4.6.2",
     "passport": "*",

```
but that eventually fails with

```
::1 - - [15/Nov/2018:14:56:37 +0000] "POST /auth/openid/return HTTP/1.1" 302 46 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"
{"name":"AzureAD: OIDC Passport Strategy","hostname":"p01166818","pid":9028,"level":30,"msg":"authentication failed due to: In _authCodeFlowHandler: failed to redeem authorization code","time":"2018-11-15T14:56:37.683Z","v":0}
_http_outgoing.js:491
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.res.setHeader (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\connect\lib\patch.js:134:22)
    at ServerResponse.res.set.res.header (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\express\lib\response.js:595:10)
    at ServerResponse.res.location (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\express\lib\response.js:725:8)
    at ServerResponse.res.redirect (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\express\lib\response.js:764:8)
    at allFailed (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport\lib\middleware\authenticate.js:145:20)
    at attempt (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport\lib\middleware\authenticate.js:180:28)
    at Strategy.strategy.fail (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport\lib\middleware\authenticate.js:297:9)
    at Strategy.failWithLog (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport-azure-ad\lib\oidcstrategy.js:1484:15)
    at async.waterfall (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport-azure-ad\lib\oidcstrategy.js:650:21)
    at C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport-azure-ad\node_modules\async\lib\async.js:52:16
    at C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport-azure-ad\node_modules\async\lib\async.js:1209:30
    at self._getAccessTokenBySecretOrAssertion (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport-azure-ad\lib\oidcstrategy.js:1194:16)
    at oauth2._request (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\passport-azure-ad\lib\oidcstrategy.js:1464:16)
    at ClientRequest.<anonymous> (C:\O365\botsample\AppModelv2-WebApp-OpenIDConnect-nodejs\node_modules\oauth\lib\oauth2.js:148:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
 
```
Proxy settings are fine:
```
 p01166818> node app.js
DEBUG global-tunnel: Found proxy in environment variable https_proxy
DEBUG global-tunnel: Found proxy in environment variable http_proxy
DEBUG global-tunnel: Proxy configuration to be used is {
  "protocol": "http:",
  "host": "localhost",
  "port": 8888,
  "proxyAuth": null
}
DEBUG global-tunnel: Creating proxying agent
DEBUG global-tunnel: Creating proxying agent
{"name":"AzureAD: OIDC Passport Strategy","hostname":"p01166818","pid":9028,"level":40,"msg":"Production environments should always validate the issuer.","time":"2018-11-15T14:56:02.912Z","v":0}
```
and I do get a login page but the final callback fails as above. I need this to work but I am stuck.

**Comment by jmprieur** [comment]
Closing as we are archiving this sample
