### ISSUE TITLE
Errors running sample...

### ISSUE THREAD

**Issue by ghost** [AzureADQuickStarts/AppModelv2-WebApp-OpenIDConnect-nodejs#8]
It shows login screen, i get to the AAD login page and I can login, it redirect back.. then booom this error...

I tried both an ORG id and a MS ID...

{"name":"AzureAD: OIDC Passport Strategy","hostname":"xxx-redacted-xxxx","pid":9050,"level":30,"msg":"v2 has no userinfo endpoint, using the content in id_token as the profile","time":"2017-04-06T01:42:43.949Z","v":0}

Error: No oid found
   at Strategy._verify (/Users/xxxx/app.js:121:19)
   at onProfileLoaded (/Users/xxxx/node_modules/passport-azure-ad/lib/oidcstrategy.js:124:27)
   at self._idTokenHandler.urlParseException (/Users/xxxx/node_modules/passport-azure-ad/lib/oidcstrategy.js:1186:16)
   at jwt.verify (/Users/xxxx/node_modules/passport-azure-ad/lib/oidcstrategy.js:966:12)
   at /Users/xxxx/node_modules/passport-azure-ad/lib/jsonWebToken.js:79:16
   at _combinedTickCallback (internal/process/next_tick.js:73:7)
   at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by lovemaths** [comment]
@kdupreez The problem can be fixed by adding 'profile' in the scope. I updated the code in the master branch. Thanks.
